###前端异步
关于前端异步的知识学习的过于碎片化，回顾起来总觉得有哪里很模糊，所以想重新梳理一下前端异步相关，巩固一下基础知识。

javascript在运行时会出现异步请求连环嵌套的情况，比如
```
setTimeout(function(){
    console.log("第一个异步回调了！")
    setTimeout(function(){
        console.log("第二个异步回调了！")
        setTimeout(function(){
            console.log("第三个异步回调了！")
            setTimeout(function(){
                console.log("第四个异步回调了！")
                setTimeout(function(){
                    console.log("第五个异步回调了！")
                },1000);
            },1000);
        },1000);
    },1000);
},1000);
```
在异步与性能中有这么个场景描述promise
就是第一个请求回来的数据直接或间接影响着下面的请求，所以只好把他们嵌套起来，这样回调才可以一步步的进行下去。这样做是没有问题的只是他们回调一个嵌套了一个就变成了所谓的'callback hell'，维护起来很不舒服。所以为了解决'回调地狱'这个问题，才研发出promise这个东西
```
　　我走到快餐店的柜台前，点了一个起士汉堡。并交了1.47美元的现金。通过点餐和付款，我为得到一个 值（起士汉堡）制造了一个请求。我发起了一个事务。
　　但是通常来说，起士汉堡不会立即到我手中。收银员交给一些东西代替我的起士汉堡：一个带有点餐排队号的收据。这个点餐号是一个“我欠你”的许诺（Promise），它保证我最终会得到我的起士汉堡。
　　于是我就拿着我的收据和点餐号。我知道它代表我的 未来的起士汉堡，所以我无需再担心它——除了挨饿！
　　在我等待的时候，我可以做其他的事情，比如给我的朋友发微信说，“嘿，一块儿吃午餐吗？我要吃起士汉堡”。
　　我已经在用我的 未来的起士汉堡 进行推理了，即便它还没有到我手中。我的大脑可以这么做是因为它将点餐号作为起士汉堡的占位符号。这个占位符号实质上使这个值 与时间无关。它是一个 未来的值。
　　最终，我听到，“113号！”。于是我愉快地拿着收据走回柜台前。我把收据递给收银员，拿回我的起士汉堡。 换句话说，一旦我的 未来的值 准备好，我就用我的许诺值换回值本身。
　　但还有另外一种可能的输出。它们叫我的号，但当我去取起士汉堡时，收银员遗憾地告诉我，“对不起，看起来我们的起士汉堡卖光了。”把这种场景下顾客有多沮丧放在一边，我们可以看到 未来的值 的一个重要性质：它们既可以表示成功也可以表示失败。
　　每次我点起士汉堡时，我都知道我要么最终得到一个起士汉堡，要么得到起士汉堡卖光的坏消息，并且不得不考虑中午吃点儿别的东西。
　　我由等待汉堡变成了等到或者等不到，这个过程不可逆，
```
上面很形象的介绍了promise，等待汉堡和得到汉堡和汉堡卖光，分别对应promise三种状态 pending fulfilled rejected

> new Promise(function(resolve,reject){...} /executor/)
  executor 是带有resolve和reject 两个参数的函数，Promise构造函数执行时立刻调用executor函数，resolve和reject两个函数作为参数传递给executor(executor函数在promise构造函数返回所建promise实例对象前被调用) resolve和reject被调用时，分别将promise的状态改为fulfilled或者reject.executor内部通常会执行一些异步操作，一旦异步操作执行完毕（成功、失败）要么调用resolve函数来将promise状态改为fulfilled 要么调用reject函数将promise改为rejected，如果在executor函数中抛出一个错误，那么该promise状态为rejected，executor函数的返回值被忽略
  pending 状态的promise对象可能会变为fulfilled 状态并传递一个值给相应的状态处理方法，也可能变为失败状态，并传递失败信息，当其中任一种情况出现时，promise对象的then方法绑定的处理方法(handlers)就会调用then包含两个参数 onfulfilled,onrejected 都是方法类型，当pending状态为fulfilled时 调用then 的onfulfilled 当为rejected时，调用then的onrejected方法，
  function mypromisefunction(url){
      return new Promise((resolve,reject)=>{
          ......
          resolve()
          reject()
      })
  }
  mypromise.then(successmessage=>{
      console.log(successmessage)
  },errormessage=>{
      console.log(errormessage)
  })

  
  方法：
   1. Promise.all(iterable), 方法返回一个新的promise对象，该对象在iterable参数对象里所有的promise对象都成功才会触发成功，一旦有任何一个iterable里面的promise对象失效则立刻触发promise对象的失败，这个心的promise对象在触发成功状态后，会把一个包含iterable里所有的promise返回值的数组作为回调的返回值，顺序跟iterable顺序相同，如果这个新的promise触发了失败状态，他会把iterable里第一个触发失败的promise对象的错误信息作为它失败错误的信息，promise.all 方法常用处理多个promise对象的状态集合
   ```
        let p1 = new Promise((resolve, reject) => {
      resolve('成功了')
    })
    
    let p2 = new Promise((resolve, reject) => {
      resolve('success')
    })
    
    let p3 = Promise.reject('失败')
    
    Promise.all([p1, p2]).then((result) => {
      console.log(result)               //['成功了', 'success']
    }).catch((error) => {
      console.log(error)
    })
    
    Promise.all([p1,p3,p2]).then((result) => {
      console.log(result)
    }).catch((error) => {
      console.log(error)      // 失败了，打出 '失败'
    })
   ```
   2. Promise.race(iterable) 追赶,任意一个子iterable被成功或者失败后，父promise马上回用子promise的成功返回值或者失败详情作为参数调用父promise绑定的事件句柄，返回promise对象
    ```
    let p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  },1000)
})

let p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('failed')
  }, 500)
})

Promise.race([p1, p2]).then((result) => {
  console.log(result)
}).catch((error) => {
  console.log(error)  // 打开的是 'failed'
})
    ```

原型:
    1. Promise.prototype.catch(onRejected):添加一个拒绝回调到当前的promise，返回一个新的promise，当这个回调函数被调用，新的promise当这个回调函数被调用，新的promise将以他的返回值来resolve
    2. Promise.prototype.then(onFulfilled,onRejected) 添加解决和拒绝回调到当前的promise，返回一个新的promise
    3. Promise.prototype.finally(onFinally):添加一个事件回调于当前promise对象，并且在原promise对象解析完毕后，返回一个新的promise对象。回调会在当前promise运行完毕后被调用,无论当前promise的状态是完成还是失败


链式调用:
连续执行两个或者多个异步操作是一个常见的需求，在上一个操作成功执行后，开始下一个的操作，并带着上一步操作所返回的结果，我们可以通过创造一个promise链来实现这种需求
then()会返回一个全新的promise 和原来不同
const promise = dosomething()
const promise2 = promise.then(successcallback,failurecallback).then(...,...)

catch 后续操作:有可能会在一个回调失败之后继续使用链式操作，即使用一个catch，这对于在链式操作中抛出一个失败后，再次进行新的操作很有用
```
new Promise((reslove,reject)=>{
    console.log('初始化')
    resolve()
}) 
 .then(()=>{
     throw new Error('哪里不对了')
     console.log('执行这个')
 })
 .catch(()=>{
     console.log('执行那个')
 })
 .then(()=>{
     console.log('执行这个 无论前面发生了什么')
 })
 初始化
 执行那个
 执行这个 无论前面发生了什么
```
注:这里是需要注意的一点是，把catch放到前面 catch执行完了后面肯定要去在执行then的，所以我们可以把catch放到链的最后，这样一旦有报错直接跳转catch 这样就可以做错误传递了

注：时序问题
为了避免意外，即使一个已经变成resolve状态的promise,传递给then 的函数也总是会被异步调用
因为then会把后面的事件变成一个微任务队列里面，
promise.resolve().then(()=>console.log(2))
console.log(1)
宏任务微任务相关再次不再赘述



async function getABC() {
let results = await Promise.all([ getValueA, getValueB, getValueC ]); 
return results;
}

感谢以下链接的分享：
https://segmentfault.com/a/1190000014631915#articleHeader1
https://segmentfault.com/a/1190000011296839
https://segmentfault.com/a/1190000015057278?utm_source=channel-newest
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise